steps:
  # Step 1: Stop the Golden VM to ensure data consistency
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'instances'
      - 'stop'
      - '${_GOLDEN_VM_NAME}'
      - '--zone=${_ZONE}'
      - '--project=${_PROJECT_ID}'

  # Step 2: Create a new custom image from the Golden VM's disk
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'images'
      - 'create'
      - 'mig-updater-image-${_BUILD_ID}'
      - '--source-disk=${_GOLDEN_VM_NAME}'
      - '--source-disk-zone=${_ZONE}'
      - '--project=${_PROJECT_ID}'
      - '--force'

  # Step 3: Create a new instance template based on the newly created image
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'instance-templates'
      - 'create'
      - 'mig-updater-template-${_BUILD_ID}'
      - '--machine-type=${_MACHINE_TYPE}'
      - '--region=${_REGION}'
      - '--image=mig-updater-image-${_BUILD_ID}'
      - '--project=${_PROJECT_ID}'
      - '--no-address'

  # Step 4: Update the Managed Instance Group (MIG) with the new instance template
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'instance-groups'
      - 'managed'
      - 'rolling-action'
      - 'start-update'
      - '${_MIG_NAME}'
      - '--version=template=mig-updater-template-${_BUILD_ID}'
      - '--zone=${_ZONE}'
      - '--project=${_PROJECT_ID}'
      - '--proactive'

# Define substitutions for easy parameterization
substitutions:
  _GOLDEN_VM_NAME: 'test'
  _MIG_NAME: 'instance-group-1'
  _ZONE: 'europe-north1-a'
  _REGION: 'europe-north1'
  _MACHINE_TYPE: 'n1-standard-4'
  _PROJECT_ID: 'yusuffeyizoglu-sandbox'
